version: "3.4"
volumes:
  db_data:
    driver: local
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: app
      MYSQL_USER: vinicius
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
